//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.20 at 01:47:17 AM IST 
//


package com.main.gedcom.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.main.gedcom.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.main.gedcom.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Indi.Deat }
     * 
     */
    public Indi.Deat createIndiDeat() {
        return new Indi.Deat();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link Indi.Chan }
     * 
     */
    public Indi.Chan createIndiChan() {
        return new Indi.Chan();
    }

    /**
     * Create an instance of {@link Gedcom }
     * 
     */
    public Gedcom createGedcom() {
        return new Gedcom();
    }

    /**
     * Create an instance of {@link Indi }
     * 
     */
    public Indi createIndi() {
        return new Indi();
    }

    /**
     * Create an instance of {@link Indi.Name }
     * 
     */
    public Indi.Name createIndiName() {
        return new Indi.Name();
    }

    /**
     * Create an instance of {@link Indi.Birth }
     * 
     */
    public Indi.Birth createIndiBirth() {
        return new Indi.Birth();
    }

    /**
     * Create an instance of {@link Fam.Marr }
     * 
     */
    public Fam.Marr createFamMarr() {
        return new Fam.Marr();
    }

    /**
     * Create an instance of {@link Fam }
     * 
     */
    public Fam createFam() {
        return new Fam();
    }

}
